### ISSUE TITLE
shellcheck crash when starting atom.io - inter-registry.js:155

### ISSUE THREAD

**Issue by Pickacho** [AtomLinter/linter-shellcheck#129]
```
C:\Users\*Myusername*\.atom\packages\linter\lib\linter-registry.js:155 [Linter] Error running ShellCheck Error: Failed to spawn command `shellcheck`. Make sure `shellcheck` is installed and on your PATH
    at C:\Users\*Myusername*\.atom\packages\linter-shellcheck\node_modules\atom-linter\lib\helpers.js:130:24
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by Arcanemagus** [comment]
As explained in the [Installation section](https://github.com/AtomLinter/linter-shellcheck#installation) of the README, you need to have `shellcheck` installed on your system _before_ you can use it in Atom through this package.

**Comment by Pickacho** [comment]
Dear Landon,

Thank you for your answer,

I have performed the installation of
Linter-shellcheck package by scoop and received -"Done"
Also tried again by installing using the Atom package manager , same error
every time.
What logs you need?
