### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by hd-deman** [AtomLinter/linter-shellcheck#24]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [linter-shellcheck](https://github.com/AtomLinter/linter-shellcheck) package, v1.0.1

### Stack Trace

Uncaught Error: spawn EACCES

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at BufferedProcess.module.exports.BufferedProcess.spawn (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
  at new BufferedProcess (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
  at /Users/deman/.atom/packages/linter-shellcheck/node_modules/atom-linter/lib/helpers.coffee:40:30
  at Object.module.exports.Helpers._exec (/Users/deman/.atom/packages/linter-shellcheck/node_modules/atom-linter/lib/helpers.coffee:22:16)
  at Object.module.exports.Helpers.exec (/Users/deman/.atom/packages/linter-shellcheck/node_modules/atom-linter/lib/helpers.coffee:13:13)
  at Object.provider.lint (/Users/deman/.atom/packages/linter-shellcheck/lib/main.coffee:38:24)
  at Promise.then._this.emitter.emit.linter (/Users/deman/.atom/packages/linter/lib/linter-registry.coffee:57:22)
  at LinterRegistry.triggerLinter (/Users/deman/.atom/packages/linter/lib/linter-registry.coffee:56:16)
  at /Users/deman/.atom/packages/linter/lib/linter-registry.coffee:50:17
  at Array.map (native)
  at /Users/deman/.atom/packages/linter/lib/linter-registry.coffee:48:27
  at process._tickCallback (node.js:367:9)

```

### Commands

```
     -9:51.7.0 find-and-replace:show (atom-text-editor.editor.mini.is-focused)
     -9:51.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -9:50.7.0 core:undo (atom-text-editor.editor.mini.is-focused)
  2x -9:41.2.0 core:copy (atom-text-editor.editor.is-focused)
     -2:00.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
  7x -0:10.1.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
  2x -0:08.3.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:07.4.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
  2x -0:06.8.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -0:06.2.0 core:paste (atom-text-editor.editor.is-focused)
  4x -0:05.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ]
  },
  "linter-shellcheck": {
    "shellcheckExecutablePath": "/usr/local/bin"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-beautify, v0.28.11
atom-color-highlight, v3.0.9
atom-ctags, v4.1.4
autoclose-html, v0.18.0
autocomplete-paths, v1.0.2
circle-ci, v0.10.0
docs-snippets, v0.8.0
file-icons, v1.6.3
file-types, v0.5.1
highlight-selected, v0.10.1
language-actionscript3, v0.3.0
language-apache, v1.3.0
language-bats, v0.1.0
language-chef, v0.5.0
language-docker, v1.1.3
language-hosts, v0.1.2
language-liquid, v0.4.0
language-nginx, v0.5.4
language-terraform, v0.5.0
language-vcl, v0.1.0
linter, v1.3.4
linter-bootlint, v0.0.6
linter-clang, v3.1.3
linter-clojure, v0.0.5
linter-coffeelint, v1.0.2
linter-cpplint, v0.1.4
linter-csslint, v1.0.5
linter-erb, v0.1.1
linter-eslint, v3.0.2
linter-flake8, v1.6.0
linter-flow, v0.1.6
linter-foodcritic, v0.4.0
linter-gjslint, v0.0.5
linter-hlint, v0.4.2
linter-htmlhint, v0.1.1
linter-javac, v1.1.0
linter-js-yaml, v1.1.1
linter-jscs, v2.0.4
linter-jshint, v1.1.5
linter-jsonlint, v0.1.4
linter-jsxhint, v0.1.2
linter-lua, v1.0.0
linter-pep257, v0.2.1
linter-pep8, v1.0.1
linter-php, v1.0.3
linter-phpcs, v1.0.6
linter-phpmd, v1.0.0
linter-puppet-lint, v0.2.9
linter-pylint, v0.2.2
linter-rubocop, v0.3.1
linter-ruby, v1.0.1
linter-scalac, v1.0.2
linter-scss-lint, v2.0.0
linter-shellcheck, v1.0.1
linter-tslint, v0.3.0
linter-xmllint, v0.0.7
minimap, v4.12.3
minimap-git-diff, v4.1.7
minimap-highlight-selected, v4.3.0
minimap-linter, v1.0.0
php-twig, v4.0.0
project-manager, v1.15.11
rspec-snippets, v0.4.0
serverspec-snippets, v0.1.0
ssh-config, v0.10.1
symbols-tree-view, v0.9.3
zentabs, v0.8.6

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
A repro case please?

**Comment by hd-deman** [comment]
repro: just upgrading linter-shellcheck

**Comment by steelbrain** [comment]
Find out the problem, You are point `shellcheckExecutablePath` at a directory instead of a file.

**Comment by StevenACoffman** [comment]
If someone has the path set to a directory like /usr/local/bin instead of a file /usr/local/bin/shellcheck, can you check if there is a file named 'shellcheck' in that directory and use that? 

Alternatively, can you display a nice informative message like 'linter-shellcheck' requires a directory instead of a path?

Also, perhaps the configuration label "Shellcheck executable path" could have a message that said 'Directory containing shellcheck executable' to make it more clear what is intended?

**Comment by steelbrain** [comment]
@StevenACoffman Well, we pipe the input to the OS and pipe the OS errors back to the users. We don't really do anything to it

**Comment by steelbrain** [comment]
EACCESS is a general error, not just in node, but in our normal terminal lives, whenever we try to execute a dir or non-executable, we get `/home: permission denied` or something similar
