### ISSUE TITLE
Error: Prelude.(!!): index too large

### ISSUE THREAD

**Issue by JD342** [AtomLinter/linter-shellcheck#46]
I'm using Atom 1.0.19 on Ubuntu 15.04, the version of linter-shellcheck is 1.1.0 and the version of shellcheck is 0.3.4. 
I'm getting the following error:
```
Error: Prelude.(!!): index too large
  at parameters.exit (/home/jed/.atom/packages/linter-shellcheck/node_modules/atom-linter/lib/helpers.js:77:20)`
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)
```
This is an example of code that reproduces that error:
```bash
function INIT() {
    SCRIPT=$1
    SCRIPTNAME=$(FILENAME "$SCRIPT")
    SCRIPTDIR=$(DIRNAME "$SCRIPT")
    DATADIR="$SCRIPTDIR/$SCRIPTNAME"
    echo SCRIPT="$SCRIPT"
    echo SCRIPTNAME="$SCRIPTNAME"
    echo SCRIPTDIR="$SCRIPTDIR"
    echo DATADIR="$DATADIR"
}
function BASENAME() {
    PATH=$1
    return "${PATH##*/}"
}
function FILENAME() {
    FILE=$1
    FILEBNAME=BASENAME "$FILE"
    return "${FILEBNAME%.*}"
}
function DIRNAME() {
    FILE=$1
    DIR=${FILE%/*}
    return BASENAME $DIR
}
INIT "$0"
```
That error is thrown when I try to add a double quote at the end of any line, for example from:
```bash
    return BASENAME $DIR
```
To:
```bash
    return BASENAME $DIR"
```

**Comment by JD342** [comment]
Closing this issue, I noticed that it is a duplicate of  #25... Sorry!
