### ISSUE TITLE
TypeError: Cannot read property 'rangeFromLineNumber' of undefined

### ISSUE THREAD

**Issue by rugk** [AtomLinter/linter-shellcheck#69]
I get multiple error messages of this when using this plugin. I am just typing in some text in `.sh` files and it appears.

```
TypeError: Cannot read property 'rangeFromLineNumber' of undefined
TypeError: Cannot read property 'rangeFromLineNumber' of undefined
    at /path/to/userprofile/.atom/packages/linter-mixed-indent/lib/main.js:42:12
    at Array.map (native)
    at Object.scanFile [as lint] (/path/to/userprofile/.atom/packages/linter-mixed-indent/lib/main.js:38:26)
    at promises.push.Promise.then._this.emitter.emit.linter (/path/to/userprofile/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /path/to/userprofile/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/path/to/userprofile/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /path/to/userprofile/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /path/to/userprofile/.atom/packages/linter/lib/editor-linter.js:86:22
    at /path/to/userprofile/.atom/packages/linter/lib/helpers.coffee:25:18
```

Atom 1.9.7

**Comment by rugk** [comment]
Ah, no, this was another plugin.
