### ISSUE TITLE
Error: Missing html/text field on Linter Response

### ISSUE THREAD

**Issue by RodideBoer** [AtomLinter/linter-shellcheck#74]
I get the following error when opening and editing a file:

```
Error: Missing html/text field on Linter Response
    at /Users/rodi/.atom/packages/linter/lib/validate.coffee:39:19
    at Array.forEach (native)
    at Object.module.exports.Validate.messages (/Users/rodi/.atom/packages/linter/lib/validate.coffee:26:14)
    at MessageRegistry.set (/Users/rodi/.atom/packages/linter/lib/message-registry.js:36:16)
    at /Users/rodi/.atom/packages/linter/lib/linter.coffee:37:17
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/rodi/.atom/packages/linter/lib/linter-registry.js:66:26
```

**Comment by Arcanemagus** [comment]
Interesting, are you able to share the file to try reproducing it?

**Comment by Arcanemagus** [comment]
Nevermind, seems to happen on any file, looking into it.

**Comment by RodideBoer** [comment]
thanks you

**Comment by Arcanemagus** [comment]
Apparently I broke this using an ES6 syntax that apparently works in some places in Coffescript... but doesn't in others. I'm getting specs working, then I'll just be converting this package to ES6 so it's usable source code...

**Comment by Arcanemagus** [comment]
v1.4.0 is out fixing this, and automatically installing Linter if it isn't already, now back to getting specs working so stuff like this doesn't get released 😛.

**Comment by RodideBoer** [comment]
great! 👍
