### ISSUE TITLE
Problem with plugin linter-shellcheck

### ISSUE THREAD

**Issue by tomaszheflik** [AtomLinter/linter-shellcheck#80]
```
Error: spawn shellcheck ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Atom version: 1.10.2

**Comment by Arcanemagus** [comment]
Do you have `shellcheck` [installed](https://github.com/koalaman/shellcheck#installing) on your system?

**Comment by tomaszheflik** [comment]
yes of course
