### ISSUE TITLE
Error: spawn shellcheck ENOENT

### ISSUE THREAD

**Issue by BuZZ-dEE** [AtomLinter/linter-shellcheck#93]
I get the following error on Antergos / Arch Linux, if I edit a bash script.

```
Error: spawn shellcheck ENOENT
Error: spawn shellcheck ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Arcanemagus** [comment]
Please ensure that you have installed [shellcheck](https://github.com/koalaman/shellcheck) on your system and it is available on your `$PATH`.

**Comment by BuZZ-dEE** [comment]
Sorry, you are right. ;)
